-- MySQL Script generated by MySQL Workbench
-- Tue Apr 29 12:21:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pharmacy_Warehouse
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `Pharmacy_Warehouse` DEFAULT CHARACTER SET utf8mb4 ;
USE `Pharmacy_Warehouse` ;

-- -----------------------------------------------------
-- Table `City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `City` ;

CREATE TABLE IF NOT EXISTS `City` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Warehouse` ;

CREATE TABLE IF NOT EXISTS `Warehouse` (
  `warehouse_id` INT NOT NULL AUTO_INCREMENT,
  `warehouse_name` VARCHAR(255) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`warehouse_id`),
  FOREIGN KEY (`city_id`) REFERENCES `City`(`city_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Pharmacy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pharmacy` ;

CREATE TABLE IF NOT EXISTS `Pharmacy` (
  `pharmacy_id` INT NOT NULL AUTO_INCREMENT,
  `city_id` INT NOT NULL,
  `pharmacy_address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pharmacy_id`),
  FOREIGN KEY (`city_id`) REFERENCES `City`(`city_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Position` ;

CREATE TABLE IF NOT EXISTS `Position` (
  `position_id` INT NOT NULL AUTO_INCREMENT,
  `position_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`position_id`))
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Warehouse_employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Warehouse_employee` ;

CREATE TABLE IF NOT EXISTS `Warehouse_employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `middle_name` VARCHAR(100) NULL,
  `passport_data` VARCHAR(255) NOT NULL,
  `position_id` INT NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `salary` DECIMAL(10,2) NOT NULL,
  `warehouse_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  FOREIGN KEY (`position_id`) REFERENCES `Position`(`position_id`),
  FOREIGN KEY (`warehouse_id`) REFERENCES `Warehouse`(`warehouse_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supplier` ;

CREATE TABLE IF NOT EXISTS `Supplier` (
  `supplier_id` INT NOT NULL AUTO_INCREMENT,
  `supplier_name` VARCHAR(255) NOT NULL,
  `company_address` VARCHAR(255) NOT NULL,
  `contact_last_name` VARCHAR(100) NOT NULL,
  `contact_first_name` VARCHAR(100) NOT NULL,
  `contact_middle_name` VARCHAR(100) NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `inn` VARCHAR(25) NOT NULL,
  `license_number` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`supplier_id`))
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Supply_to_warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supply_to_warehouse` ;

CREATE TABLE IF NOT EXISTS `Supply_to_warehouse` (
  `supply_id` INT NOT NULL AUTO_INCREMENT,
  `supplier_id` INT NOT NULL,
  `supply_date` DATE NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`supply_id`),
  FOREIGN KEY (`supplier_id`) REFERENCES `Supplier`(`supplier_id`),
  FOREIGN KEY (`employee_id`) REFERENCES `Warehouse_employee`(`employee_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Medicine_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Medicine_group` ;

CREATE TABLE IF NOT EXISTS `Medicine_group` (
  `group_id` INT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Manufacturer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Manufacturer` ;

CREATE TABLE IF NOT EXISTS `Manufacturer` (
  `manufacturer_id` INT NOT NULL AUTO_INCREMENT,
  `manufacturer_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`manufacturer_id`))
ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Medicine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Medicine` ;

CREATE TABLE IF NOT EXISTS `Medicine` (
  `medicine_id` INT NOT NULL AUTO_INCREMENT,
  `medicine_name` VARCHAR(255) NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `purpose` VARCHAR(1000) NOT NULL,
  `group_id` INT NOT NULL,
  `unit` VARCHAR(50) NOT NULL,
  `purchase_price` DECIMAL(10,2) NOT NULL,
  `selling_price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`medicine_id`),
  FOREIGN KEY (`manufacturer_id`) REFERENCES `Manufacturer`(`manufacturer_id`),
  FOREIGN KEY (`group_id`) REFERENCES `Medicine_group`(`group_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Supply_to_pharmacy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supply_to_pharmacy` ;

CREATE TABLE IF NOT EXISTS `Supply_to_pharmacy` (
  `id_supply` INT NOT NULL AUTO_INCREMENT,
  `pharmacy_id` INT NOT NULL,
  `supply_date` DATE NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id_supply`),
  FOREIGN KEY (`pharmacy_id`) REFERENCES `Pharmacy`(`pharmacy_id`),
  FOREIGN KEY (`employee_id`) REFERENCES `Warehouse_employee`(`employee_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Warehouse_stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Warehouse_stock` ;

CREATE TABLE IF NOT EXISTS `Warehouse_stock` (
  `warehouse_id` INT NOT NULL,
  `medicine_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`warehouse_id`, `medicine_id`),
  FOREIGN KEY (`warehouse_id`) REFERENCES `Warehouse`(`warehouse_id`),
  FOREIGN KEY (`medicine_id`) REFERENCES `Medicine`(`medicine_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Supply_warehouse_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supply_warehouse_items` ;

CREATE TABLE IF NOT EXISTS `Supply_warehouse_items` (
  `supply_id` INT NOT NULL,
  `medicine_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`supply_id`, `medicine_id`),
  FOREIGN KEY (`supply_id`) REFERENCES `Supply_to_warehouse`(`supply_id`),
  FOREIGN KEY (`medicine_id`) REFERENCES `Medicine`(`medicine_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `Supply_pharmacy_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supply_pharmacy_items` ;

CREATE TABLE IF NOT EXISTS `Supply_pharmacy_items` (
  `id_supply` INT NOT NULL,
  `medicine_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id_supply`, `medicine_id`),
  FOREIGN KEY (`id_supply`) REFERENCES `Supply_to_pharmacy`(`id_supply`),
  FOREIGN KEY (`medicine_id`) REFERENCES `Medicine`(`medicine_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
